
package lcc030517;

import java.awt.Graphics;
import java.awt.Image;
//import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;


public class Imagenes extends javax.swing.JFrame {

    int f=0;
    Graphics g;
    Image img1,img2,img3,img4,img5;
//    Toolkit tk = Toolkit.getDefaultToolkit();
        
    public Imagenes() {
        initComponents();

        //needs to be an "image" folder in the project folder
        File A = new File("Img/Muestra/A.jpg"); 
        File B = new File("Img/Muestra/B.jpg");
        File C = new File("Img/Muestra/C.jpg");
        File D = new File("Img/Muestra/D.jpg");
        File E = new File("Img/Muestra/E.jpg");
        
        try {
                img1 = ImageIO.read(new File(A.toURI()));
                img2 = ImageIO.read(new File(B.toURI()));
                img3 = ImageIO.read(new File(C.toURI()));
                img4 = ImageIO.read(new File(D.toURI()));
                img5 = ImageIO.read(new File(E.toURI()));
            } catch (IOException e) {
            }
      
/*
        img1 = tk.getImage("A.jpg");
        img2 = tk.getImage("B.jpg");
        img3 = tk.getImage("C.jpg");
        img4 = tk.getImage("D.jpg");
        img5 = tk.getImage("D.jpg");
*/                
        g=MiniPantalla.getGraphics();    // Hace que todo g se muestre en la mini pantalla [==].

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        MiniPantalla = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danilo Abellá\\Documents\\NetBeansProjects\\LCC030517\\Img\\Punteros\\Fin.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fin(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danilo Abellá\\Documents\\NetBeansProjects\\LCC030517\\Img\\Punteros\\F.png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Der(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danilo Abellá\\Documents\\NetBeansProjects\\LCC030517\\Img\\Punteros\\Inicio.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inicio(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danilo Abellá\\Documents\\NetBeansProjects\\LCC030517\\Img\\Punteros\\Izq.png")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Izq(evt);
            }
        });

        MiniPantalla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout MiniPantallaLayout = new javax.swing.GroupLayout(MiniPantalla);
        MiniPantalla.setLayout(MiniPantallaLayout);
        MiniPantallaLayout.setHorizontalGroup(
            MiniPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MiniPantallaLayout.setVerticalGroup(
            MiniPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danilo Abellá\\Documents\\NetBeansProjects\\LCC030517\\Img\\Punteros\\X.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MiniPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MiniPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Izq(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Izq
        
        if (f>0)
        {
            f--;
            
            if(f==0){
                g.drawImage(img1, 1, 1, MiniPantalla.getWidth()-2, MiniPantalla.getHeight()-2,this);
            }
                       
            if(f==1){
                g.drawImage(img2, 1, 1, MiniPantalla.getWidth()-2, MiniPantalla.getHeight()-2,this);
            }
            
            if(f==2){
                g.drawImage(img3, 1, 1, MiniPantalla.getWidth()-2, MiniPantalla.getHeight()-2,this);
            }
                        
            if(f==3){
                g.drawImage(img4, 1, 1, MiniPantalla.getWidth()-2, MiniPantalla.getHeight()-2,this);
            }
            
            if(f==4){
                g.drawImage(img5, 1, 1, MiniPantalla.getWidth()-2, MiniPantalla.getHeight()-2,this);
            }
   
        }
    }//GEN-LAST:event_Izq

    private void Exit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit
         System.exit(0);
    }//GEN-LAST:event_Exit

    private void Inicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inicio
        f=0;
        g.drawImage(img1, 1, 1, MiniPantalla.getWidth()-2, MiniPantalla.getHeight()-2,this);
    }//GEN-LAST:event_Inicio

    private void Der(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Der
        
        if (f<4)
        {
            f++;
            
            if(f==0){
                g.drawImage(img1, 1, 1, MiniPantalla.getWidth()-2, MiniPantalla.getHeight()-2,this);
            }
                      
            if(f==1){
                g.drawImage(img2, 1, 1, MiniPantalla.getWidth()-2, MiniPantalla.getHeight()-2,this);
            }
            
            if(f==2){
                g.drawImage(img3, 1, 1, MiniPantalla.getWidth()-2, MiniPantalla.getHeight()-2,this);
            }
                        
            if(f==3){
                g.drawImage(img4, 1, 1, MiniPantalla.getWidth()-2, MiniPantalla.getHeight()-2,this);
            }
            
            if(f==4){
                g.drawImage(img5, 1, 1, MiniPantalla.getWidth()-2, MiniPantalla.getHeight()-2,this);
            }
        }
    }//GEN-LAST:event_Der

    private void Fin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fin
        f=5;
        g.drawImage(img5, 1, 1, MiniPantalla.getWidth()-2, MiniPantalla.getHeight()-2,this);
    }//GEN-LAST:event_Fin


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imagenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MiniPantalla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
